# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_2(object):
    def setupUi(self, register_2):
        register_2.setObjectName("register_2")
        register_2.resize(844, 719)
        self.centralwidget = QtWidgets.QWidget(register_2)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.Button_exit.setGeometry(QtCore.QRect(660, 590, 93, 28))
        self.Button_exit.setObjectName("Button_exit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 40, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 200, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 60, 391, 149))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(70, 35))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(70, 35))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(70, 35))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.register_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.register_id.setObjectName("register_id")
        self.gridLayout.addWidget(self.register_id, 0, 1, 1, 1)
        self.register_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.register_password.setObjectName("register_password")
        self.gridLayout.addWidget(self.register_password, 1, 1, 1, 1)
        self.confirm_pas = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirm_pas.setObjectName("confirm_pas")
        self.gridLayout.addWidget(self.confirm_pas, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(640, 180, 201, 16))
        self.label_10.setObjectName("label_10")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(242, 262, 391, 261))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(70, 35))
        self.label_4.setMaximumSize(QtCore.QSize(70, 35))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(70, 35))
        self.label_5.setMaximumSize(QtCore.QSize(70, 35))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.radioM = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioM.setObjectName("radioM")
        self.gridLayout_2.addWidget(self.radioM, 1, 1, 1, 1)
        self.radioW = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioW.setObjectName("radioW")
        self.gridLayout_2.addWidget(self.radioW, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setMaximumSize(QtCore.QSize(70, 35))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.tel = QtWidgets.QLineEdit(self.layoutWidget1)
        self.tel.setObjectName("tel")
        self.gridLayout_2.addWidget(self.tel, 2, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setMaximumSize(QtCore.QSize(70, 35))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 3, 1, 1, 2)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 550, 280, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_register = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_register.setObjectName("Button_register")
        self.horizontalLayout.addWidget(self.Button_register)
        spacerItem = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Button_returnlogin = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_returnlogin.setObjectName("Button_returnlogin")
        self.horizontalLayout.addWidget(self.Button_returnlogin)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(640, 80, 161, 16))
        self.label_11.setObjectName("label_11")
        register_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(register_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 26))
        self.menubar.setObjectName("menubar")
        register_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(register_2)
        self.statusbar.setObjectName("statusbar")
        register_2.setStatusBar(self.statusbar)

        self.retranslateUi(register_2)
        self.Button_exit.clicked['bool'].connect(register_2.close)
        QtCore.QMetaObject.connectSlotsByName(register_2)

    def retranslateUi(self, register_2):
        _translate = QtCore.QCoreApplication.translate
        register_2.setWindowTitle(_translate("register_2", "Register"))
        self.Button_exit.setText(_translate("register_2", "退出"))
        self.label_6.setText(_translate("register_2", "账号信息"))
        self.label_7.setText(_translate("register_2", "个人信息"))
        self.label_3.setText(_translate("register_2", "确认密码："))
        self.label.setText(_translate("register_2", "密码："))
        self.label_2.setText(_translate("register_2", "账号："))
        self.label_10.setText(_translate("register_2", "两次密码不一致，重新输入"))
        self.label_4.setText(_translate("register_2", "姓名："))
        self.label_5.setText(_translate("register_2", "性别："))
        self.radioM.setText(_translate("register_2", "男"))
        self.radioW.setText(_translate("register_2", "女"))
        self.label_8.setText(_translate("register_2", "手机："))
        self.label_9.setText(_translate("register_2", "备注："))
        self.Button_register.setText(_translate("register_2", "注册"))
        self.Button_returnlogin.setText(_translate("register_2", "返回登陆"))
        self.label_11.setText(_translate("register_2", "账号已存在，重新输入"))

        self.label_10.setVisible(False)
        self.label_11.setVisible(False)